name: Publish

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

  # workflow_dispatch:

jobs:
  publish:
    name: Build and Publish
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm run build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # BRANCH: gh-pages
          FOLDER: dist
